spring:
  datasource:
    primary:
      url: jdbc:h2:mem:primary
      username: sa
      password: password
      driverClassName: org.h2.Driver
    secondary:
      url: jdbc:h2:mem:secondary
      username: sa
      password: password
      driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true